name: update

on:
  schedule:
    - cron: "0 8 * * 0"
  workflow_dispatch:
    inputs:
      message:
        description: "Message for build"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: "master"
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: |
        echo ${{ secrets.GITHUB_TOKEN }} >> access_token.txt
        pip install requests && python list2md.py
    - name: update the list
      env:
        GITHUB_USER: "stradivari96"
        GITHUB_EMAIL: "xiangchenchen96@gmail.com"
      run: |
        git config user.name "${GITHUB_USER}"
        git config user.email "${GITHUB_EMAIL}"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
        git commit -am "chore: auto update"
        git push -u origin master
